In [29]:
import pandas as pd
import numpy as np

In [30]:
df=pd.read_csv("HR_PJ_messy_dataset.csv")
df

,Unnamed: 0,Full_Name,Age,Gender,Department,Job_Title,Education,Hire_Date,Salary,Years_At_Company,Job_Satisfaction,Performance_Rating,Monthly_Hours,Attrition,Region,Payment_Method,Phone,Email
0,EMP00001,Employee_1,59,fm,Mktg,analyst,Bachelors,11-01-2021,"25,000",7.0,5.0,4.0,60.0,NO,EUR,direct deposit,608.834.6257,employee_1@company.com
1,EMP00002,Employee_2,NaN,M,IT,Director,MASTER,17-06-2022,"25,000",12.0,2.0,1.0,47.0,no,N. America,CASH,774-262-5380,employee_2@company.com
2,EMP00003,Employee_3,35,M,LEGAL,manager,Bachelors,07-07-2023,"90,443",15.0,3.0,2.0,68.0,No,Apac,cash,334 259 8799,employee_3@company.com
3,EMP00004,Employee_4,28,F,NaN,assoc,HS,24-02-2013,$25000,11.0,5.0,5.0,53.0,No,Asia Pacific,direct deposit,671 938 8168,employee_4@company.com
4,EMP00005,Employee_5,41,NaN,Finance,director,associate,17-10-2013,"76,538",16.0,5.0,2.0,42.0,Stayed,Mid East,Direct Deposit,937 303 4682,employee_5@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12995,EMP12996,Employee_12996,35,fm,sales,assoc,Bachelor,07-23-2020,"65,371",11.0,3.0,2.0,35.0,Stayed,NaN,cash,592.734.6999,employee_12996@company.com
12996,EMP12997,Employee_12997,NaN,Female,NaN,Consult,NaN,04-06-2018,65252,19.0,3.0,2.0,46.0,yes,N. America,wire transfer,724 204 7512,employee_12997@company.com
12997,EMP12998,Employee_12998,27,Female,Marketing,Assoc,PHD,08-10-2014,$102818,6.0,1.0,1.0,37.0,Stayed,asia pacific,CHK,NaN,employee_12998@company.com
12998,EMP12999,Employee_12999,31,male,sales,analyst,bachelor,18-Dec-14,"74,565",11.0,3.0,1.0,43.0,NO,LATAM,Wire Transfer,391-560-4627,employee_12999@company.com
12999,EMP13000,Employee_13000,60,FEMALE,Engg,ANALYST,Bachelors,10-05-2012,68124,7.0,4.0,5.0,53.0,NO,Apac,DD,(536) 908-5402,employee_13000@company.com

In [31]:
print(df.head())
print(df.shape)
print(df.info())

  Unnamed: 0   Full_Name  Age Gender Department Job_Title  Education  \
0   EMP00001  Employee_1   59     fm       Mktg   analyst  Bachelors
1   EMP00002  Employee_2  NaN      M         IT  Director     MASTER
2   EMP00003  Employee_3   35      M      LEGAL   manager  Bachelors
3   EMP00004  Employee_4   28      F        NaN     assoc         HS
4   EMP00005  Employee_5   41    NaN    Finance  director  associate

    Hire_Date  Salary  Years_At_Company  Job_Satisfaction  Performance_Rating  \
0  11-01-2021  25,000               7.0               5.0                 4.0
1  17-06-2022  25,000              12.0               2.0                 1.0
2  07-07-2023  90,443              15.0               3.0                 2.0
3  24-02-2013  $25000              11.0               5.0                 5.0
4  17-10-2013  76,538              16.0               5.0                 2.0

   Monthly_Hours Attrition        Region  Payment_Method         Phone  \
0           60.0        NO           EUR  direct deposit  608.834.6257
1           47.0        no    N. America            CASH  774-262-5380
2           68.0        No          Apac            cash  334 259 8799
3           53.0        No  Asia Pacific  direct deposit  671 938 8168
4           42.0    Stayed      Mid East  Direct Deposit  937 303 4682

                    Email
0  employee_1@company.com
1  employee_2@company.com
2  employee_3@company.com
3  employee_4@company.com
4  employee_5@company.com
(13000, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          13000 non-null  object
 1   Full_Name           13000 non-null  object
 2   Age                 12466 non-null  object
 3   Gender              12601 non-null  object
 4   Department          12597 non-null  object
 5   Job_Title           12584 non-null  object
 6   Education           12497 non-null  object
 7   Hire_Date           12459 non-null  object
 8   Salary              12433 non-null  object
 9   Years_At_Company    12598 non-null  float64
 10  Job_Satisfaction    12617 non-null  float64
 11  Performance_Rating  12601 non-null  float64
 12  Monthly_Hours       12618 non-null  float64
 13  Attrition           12602 non-null  object
 14  Region              11926 non-null  object
 15  Payment_Method      12634 non-null  object
 16  Phone               12335 non-null  object
 17  Email               12341 non-null  object
dtypes: float64(4), object(14)
memory usage: 1.8+ MB
None

In [32]:
df_original = df.copy()

In [33]:
df.columns=(df.columns.str.strip().str.replace(" ","_"))
df.rename(columns={"Unnamed:_0":"EmployeeID"},inplace=True)
df

,EmployeeID,Full_Name,Age,Gender,Department,Job_Title,Education,Hire_Date,Salary,Years_At_Company,Job_Satisfaction,Performance_Rating,Monthly_Hours,Attrition,Region,Payment_Method,Phone,Email
0,EMP00001,Employee_1,59,fm,Mktg,analyst,Bachelors,11-01-2021,"25,000",7.0,5.0,4.0,60.0,NO,EUR,direct deposit,608.834.6257,employee_1@company.com
1,EMP00002,Employee_2,NaN,M,IT,Director,MASTER,17-06-2022,"25,000",12.0,2.0,1.0,47.0,no,N. America,CASH,774-262-5380,employee_2@company.com
2,EMP00003,Employee_3,35,M,LEGAL,manager,Bachelors,07-07-2023,"90,443",15.0,3.0,2.0,68.0,No,Apac,cash,334 259 8799,employee_3@company.com
3,EMP00004,Employee_4,28,F,NaN,assoc,HS,24-02-2013,$25000,11.0,5.0,5.0,53.0,No,Asia Pacific,direct deposit,671 938 8168,employee_4@company.com
4,EMP00005,Employee_5,41,NaN,Finance,director,associate,17-10-2013,"76,538",16.0,5.0,2.0,42.0,Stayed,Mid East,Direct Deposit,937 303 4682,employee_5@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12995,EMP12996,Employee_12996,35,fm,sales,assoc,Bachelor,07-23-2020,"65,371",11.0,3.0,2.0,35.0,Stayed,NaN,cash,592.734.6999,employee_12996@company.com
12996,EMP12997,Employee_12997,NaN,Female,NaN,Consult,NaN,04-06-2018,65252,19.0,3.0,2.0,46.0,yes,N. America,wire transfer,724 204 7512,employee_12997@company.com
12997,EMP12998,Employee_12998,27,Female,Marketing,Assoc,PHD,08-10-2014,$102818,6.0,1.0,1.0,37.0,Stayed,asia pacific,CHK,NaN,employee_12998@company.com
12998,EMP12999,Employee_12999,31,male,sales,analyst,bachelor,18-Dec-14,"74,565",11.0,3.0,1.0,43.0,NO,LATAM,Wire Transfer,391-560-4627,employee_12999@company.com
12999,EMP13000,Employee_13000,60,FEMALE,Engg,ANALYST,Bachelors,10-05-2012,68124,7.0,4.0,5.0,53.0,NO,Apac,DD,(536) 908-5402,employee_13000@company.com

In [34]:
duplicate=df.duplicated().sum()
print("Dupplicate Rows",duplicate)

Dupplicate Rows 0

In [35]:
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                    534
Gender                 399
Department             403
Job_Title              416
Education              503
Hire_Date              541
Salary                 567
Years_At_Company       402
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [36]:
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Age"]=df["Age"].astype(int)
df.loc[df["Age"]<18,"Age"]=19
df.loc[df["Age"]>60,"Age"]=60
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                      0
Gender                 399
Department             403
Job_Title              416
Education              503
Hire_Date              541
Salary                 567
Years_At_Company       402
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [37]:
text_columns=["Gender","Department","Job_Title","Education","Attrition","Region","Payment_Method"]
for col in text_columns:
    df[col]=(df[col].astype(str).str.strip().str.title().replace("Nan",pd.NA))
df

,EmployeeID,Full_Name,Age,Gender,Department,Job_Title,Education,Hire_Date,Salary,Years_At_Company,Job_Satisfaction,Performance_Rating,Monthly_Hours,Attrition,Region,Payment_Method,Phone,Email
0,EMP00001,Employee_1,59,Fm,Mktg,Analyst,Bachelors,11-01-2021,"25,000",7.0,5.0,4.0,60.0,No,Eur,Direct Deposit,608.834.6257,employee_1@company.com
1,EMP00002,Employee_2,41,M,It,Director,Master,17-06-2022,"25,000",12.0,2.0,1.0,47.0,No,N. America,Cash,774-262-5380,employee_2@company.com
2,EMP00003,Employee_3,35,M,Legal,Manager,Bachelors,07-07-2023,"90,443",15.0,3.0,2.0,68.0,No,Apac,Cash,334 259 8799,employee_3@company.com
3,EMP00004,Employee_4,28,F,<NA>,Assoc,Hs,24-02-2013,$25000,11.0,5.0,5.0,53.0,No,Asia Pacific,Direct Deposit,671 938 8168,employee_4@company.com
4,EMP00005,Employee_5,41,<NA>,Finance,Director,Associate,17-10-2013,"76,538",16.0,5.0,2.0,42.0,Stayed,Mid East,Direct Deposit,937 303 4682,employee_5@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12995,EMP12996,Employee_12996,35,Fm,Sales,Assoc,Bachelor,07-23-2020,"65,371",11.0,3.0,2.0,35.0,Stayed,<NA>,Cash,592.734.6999,employee_12996@company.com
12996,EMP12997,Employee_12997,41,Female,<NA>,Consult,<NA>,04-06-2018,65252,19.0,3.0,2.0,46.0,Yes,N. America,Wire Transfer,724 204 7512,employee_12997@company.com
12997,EMP12998,Employee_12998,27,Female,Marketing,Assoc,Phd,08-10-2014,$102818,6.0,1.0,1.0,37.0,Stayed,Asia Pacific,Chk,NaN,employee_12998@company.com
12998,EMP12999,Employee_12999,31,Male,Sales,Analyst,Bachelor,18-Dec-14,"74,565",11.0,3.0,1.0,43.0,No,Latam,Wire Transfer,391-560-4627,employee_12999@company.com
12999,EMP13000,Employee_13000,60,Female,Engg,Analyst,Bachelors,10-05-2012,68124,7.0,4.0,5.0,53.0,No,Apac,Dd,(536) 908-5402,employee_13000@company.com

In [38]:
df.dtypes

EmployeeID             object
Full_Name              object
Age                     int64
Gender                 object
Department             object
Job_Title              object
Education              object
Hire_Date              object
Salary                 object
Years_At_Company      float64
Job_Satisfaction      float64
Performance_Rating    float64
Monthly_Hours         float64
Attrition              object
Region                 object
Payment_Method         object
Phone                  object
Email                  object
dtype: object

In [39]:
df["Gender"].value_counts(dropna=False)
#df["Gender"] = df["Gender"].replace("Nan", pd.NA)
df["Gender"]=df["Gender"].replace({"Fmale":"Female","Fm":"Female","M":"Male","F":"Female"})
df["Gender"]=df["Gender"].fillna("Female")
df
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department             403
Job_Title              416
Education              503
Hire_Date              541
Salary                 567
Years_At_Company       402
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [40]:
df["Department"].value_counts(dropna=False)
df["Department"] = df["Department"].replace({"It": "IT","I.T": "IT","Hr": "HR","H.R": "HR","Engg": "Engineering","Mktg": "Marketing","Ops": "Operations"})
m=df["Department"].mode()[0]
print(m)
df["Department"]=df["Department"].fillna(m)
df
df.isnull().sum()

Engineering

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title              416
Education              503
Hire_Date              541
Salary                 567
Years_At_Company       402
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [41]:
df["Job_Title"].value_counts(dropna=False)
df["Job_Title"]=df["Job_Title"].replace({"Assoc":"Associate","Vp":"VP","V.P":"VP","Snr Analyst":"Senior Analyst","Sr Manager":"Senior Manager","Mgr":"Manager",
                                         "Int":"Intern","Dir":"Director","Consult":"Consultant"})
m=df["Job_Title"].mode()[0]
print(m)
df["Job_Title"]=df["Job_Title"].fillna(m)
df["Job_Title"].value_counts(dropna=False)
df
df.isnull().sum()

Analyst

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title                0
Education              503
Hire_Date              541
Salary                 567
Years_At_Company       402
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [42]:
df["Education"].value_counts(dropna=False)
df["Education"] = df["Education"].replace({
    "Bachelors": "Bachelor",
    "Bachelor": "Bachelor",

    "Masters": "Master",
    "Master": "Master",

    "Phd": "PhD",
    "P.H.D": "PhD",

    "Hs": "High School",
    "Highschool": "High School",

    "Assoc Degree": "Associate",
    "Associate": "Associate"
})
df["Education"]=df["Education"].fillna(df["Education"].mode()[0])
df
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title                0
Education                0
Hire_Date              541
Salary                 567
Years_At_Company       402
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [43]:
df["Hire_Date"].value_counts(dropna=False)
df["Hire_Date"]=df["Hire_Date"].replace(["--","TBD","Unknown"],pd.NA)
df["Hire_Date"]=pd.to_datetime(df["Hire_Date"],errors="coerce",dayfirst=True)
df["Hire_Date"]=df["Hire_Date"].fillna(df["Hire_Date"].mode()[0])
df.dtypes
df.isnull().sum()
df

,EmployeeID,Full_Name,Age,Gender,Department,Job_Title,Education,Hire_Date,Salary,Years_At_Company,Job_Satisfaction,Performance_Rating,Monthly_Hours,Attrition,Region,Payment_Method,Phone,Email
0,EMP00001,Employee_1,59,Female,Marketing,Analyst,Bachelor,2021-01-11,"25,000",7.0,5.0,4.0,60.0,No,Eur,Direct Deposit,608.834.6257,employee_1@company.com
1,EMP00002,Employee_2,41,Male,IT,Director,Master,2022-06-17,"25,000",12.0,2.0,1.0,47.0,No,N. America,Cash,774-262-5380,employee_2@company.com
2,EMP00003,Employee_3,35,Male,Legal,Manager,Bachelor,2023-07-07,"90,443",15.0,3.0,2.0,68.0,No,Apac,Cash,334 259 8799,employee_3@company.com
3,EMP00004,Employee_4,28,Female,Engineering,Associate,High School,2013-02-24,$25000,11.0,5.0,5.0,53.0,No,Asia Pacific,Direct Deposit,671 938 8168,employee_4@company.com
4,EMP00005,Employee_5,41,Female,Finance,Director,Associate,2013-10-17,"76,538",16.0,5.0,2.0,42.0,Stayed,Mid East,Direct Deposit,937 303 4682,employee_5@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12995,EMP12996,Employee_12996,35,Female,Sales,Associate,Bachelor,2015-05-05,"65,371",11.0,3.0,2.0,35.0,Stayed,<NA>,Cash,592.734.6999,employee_12996@company.com
12996,EMP12997,Employee_12997,41,Female,Engineering,Consultant,High School,2018-06-04,65252,19.0,3.0,2.0,46.0,Yes,N. America,Wire Transfer,724 204 7512,employee_12997@company.com
12997,EMP12998,Employee_12998,27,Female,Marketing,Associate,PhD,2014-10-08,$102818,6.0,1.0,1.0,37.0,Stayed,Asia Pacific,Chk,NaN,employee_12998@company.com
12998,EMP12999,Employee_12999,31,Male,Sales,Analyst,Bachelor,2015-05-05,"74,565",11.0,3.0,1.0,43.0,No,Latam,Wire Transfer,391-560-4627,employee_12999@company.com
12999,EMP13000,Employee_13000,60,Female,Engineering,Analyst,Bachelor,2012-05-10,68124,7.0,4.0,5.0,53.0,No,Apac,Dd,(536) 908-5402,employee_13000@company.com

In [44]:
print(df["Salary"].value_counts(dropna=False))
df["Salary"] = (
    df["Salary"]
    .astype(str)
    .str.replace(",", "")
    .str.replace("$", "", regex=False))
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Salary"]=df["Salary"].fillna(df["Salary"].mode()[0])
df.isnull().sum()

Salary
NaN       567
25000     173
$25000    169
25.0k     168
25,000    160
         ...
63430       1
$82859      1
$63336      1
$70164      1
68124       1
Name: count, Length: 9515, dtype: int64

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title                0
Education                0
Hire_Date                0
Salary                   0
Years_At_Company       402
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [45]:
df["Years_At_Company"].value_counts(dropna=False)
df["Years_At_Company"]=df["Years_At_Company"].fillna(0)
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title                0
Education                0
Hire_Date                0
Salary                   0
Years_At_Company         0
Job_Satisfaction       383
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [46]:
df["Job_Satisfaction"]=df["Job_Satisfaction"].fillna(df["Job_Satisfaction"].mode()[0])
df["Job_Satisfaction"].value_counts(dropna=False)
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title                0
Education                0
Hire_Date                0
Salary                   0
Years_At_Company         0
Job_Satisfaction         0
Performance_Rating     399
Monthly_Hours          382
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [47]:
df["Performance_Rating"]=df["Performance_Rating"].fillna(df["Performance_Rating"].mode()[0])
df["Performance_Rating"].value_counts(dropna=False)
#df.isnull().sum()

Performance_Rating
4.0    3003
1.0    2551
3.0    2490
2.0    2488
5.0    2468
Name: count, dtype: int64

In [48]:
df["Monthly_Hours"].value_counts(dropna=False)
df["Monthly_Hours"] = df["Monthly_Hours"].fillna(df["Monthly_Hours"].median())
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title                0
Education                0
Hire_Date                0
Salary                   0
Years_At_Company         0
Job_Satisfaction         0
Performance_Rating       0
Monthly_Hours            0
Attrition              398
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [49]:
df["Attrition"].value_counts()
df["Attrition"] = df["Attrition"].replace({"Left": "Yes","Y": "Yes","Stayed": "No","N": "No"})
df["Attrition"] = df["Attrition"].fillna("No")
df.isnull().sum()

EmployeeID               0
Full_Name                0
Age                      0
Gender                   0
Department               0
Job_Title                0
Education                0
Hire_Date                0
Salary                   0
Years_At_Company         0
Job_Satisfaction         0
Performance_Rating       0
Monthly_Hours            0
Attrition                0
Region                1074
Payment_Method         366
Phone                  665
Email                  659
dtype: int64

In [50]:
df["Region"].value_counts()
mapping = {"Apac": "Asia Pacific","N. America": "North America","Latam": "Latin America","Eur": "Europe","Mid East": "Middle East","Me": "Middle East"}
df["Region"] = df["Region"].replace(mapping)
df["Region"] = df["Region"].fillna(df["Region"].mode()[0])
df.isnull().sum()

EmployeeID              0
Full_Name               0
Age                     0
Gender                  0
Department              0
Job_Title               0
Education               0
Hire_Date               0
Salary                  0
Years_At_Company        0
Job_Satisfaction        0
Performance_Rating      0
Monthly_Hours           0
Attrition               0
Region                  0
Payment_Method        366
Phone                 665
Email                 659
dtype: int64

In [51]:
df["Payment_Method"].value_counts(dropna=False)
mapping = {"Wire Transfer": "Wire Transfer","Wire": "Wire Transfer","Check": "Check","Chk": "Check","Direct Deposit": "Direct Deposit","Dd": "Direct Deposit","Cash": "Cash"}
df["Payment_Method"] = df["Payment_Method"].replace(mapping)
p=df["Payment_Method"].mode()[0]
print(p)
df["Payment_Method"] = df["Payment_Method"].fillna(p)

Wire Transfer

In [52]:
df["Phone"].value_counts(dropna=False)
df=df.drop(columns=["Phone"])

In [53]:
df.dtypes

EmployeeID                    object
Full_Name                     object
Age                            int64
Gender                        object
Department                    object
Job_Title                     object
Education                     object
Hire_Date             datetime64[ns]
Salary                       float64
Years_At_Company             float64
Job_Satisfaction             float64
Performance_Rating           float64
Monthly_Hours                float64
Attrition                     object
Region                        object
Payment_Method                object
Email                         object
dtype: object

In [54]:
df["Email"]=df["Email"].fillna("Unknown")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EmployeeID          13000 non-null  object
 1   Full_Name           13000 non-null  object
 2   Age                 13000 non-null  int64
 3   Gender              13000 non-null  object
 4   Department          13000 non-null  object
 5   Job_Title           13000 non-null  object
 6   Education           13000 non-null  object
 7   Hire_Date           13000 non-null  datetime64[ns]
 8   Salary              13000 non-null  float64
 9   Years_At_Company    13000 non-null  float64
 10  Job_Satisfaction    13000 non-null  float64
 11  Performance_Rating  13000 non-null  float64
 12  Monthly_Hours       13000 non-null  float64
 13  Attrition           13000 non-null  object
 14  Region              13000 non-null  object
 15  Payment_Method      13000 non-null  object
 16  Email               13000 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(1), object(10)
memory usage: 1.7+ MB

In [55]:
df.isnull().sum()

EmployeeID            0
Full_Name             0
Age                   0
Gender                0
Department            0
Job_Title             0
Education             0
Hire_Date             0
Salary                0
Years_At_Company      0
Job_Satisfaction      0
Performance_Rating    0
Monthly_Hours         0
Attrition             0
Region                0
Payment_Method        0
Email                 0
dtype: int64

In [56]:
df.dtypes

EmployeeID                    object
Full_Name                     object
Age                            int64
Gender                        object
Department                    object
Job_Title                     object
Education                     object
Hire_Date             datetime64[ns]
Salary                       float64
Years_At_Company             float64
Job_Satisfaction             float64
Performance_Rating           float64
Monthly_Hours                float64
Attrition                     object
Region                        object
Payment_Method                object
Email                         object
dtype: object

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
for col in df.select_dtypes(include="object"):
    print(col)
    print(df[col].value_counts(dropna=False))
    print("-"*30)

EmployeeID
EmployeeID
EMP00001    1
EMP08671    1
EMP08661    1
EMP08662    1
EMP08663    1
           ..
EMP04337    1
EMP04338    1
EMP04339    1
EMP04340    1
EMP13000    1
Name: count, Length: 13000, dtype: int64
------------------------------
Full_Name
Full_Name
Employee_1        1
Employee_8671     1
Employee_8661     1
Employee_8662     1
Employee_8663     1
                 ..
Employee_4337     1
Employee_4338     1
Employee_4339     1
Employee_4340     1
Employee_13000    1
Name: count, Length: 13000, dtype: int64
------------------------------
Gender
Gender
Female    7990
Male      5010
Name: count, dtype: int64
------------------------------
Department
Department
Engineering    2407
Marketing      1548
Legal          1536
IT             1533
Operations     1507
HR             1498
Finance        1497
Sales          1474
Name: count, dtype: int64
------------------------------
Job_Title
Job_Title
Analyst           1858
Associate         1427
Consultant        1409
Manager           1396
VP                1387
Intern            1359
Director          1357
Senior Analyst     977
Lead               947
Senior Manager     883
Name: count, dtype: int64
------------------------------
Education
Education
High School    3216
Master         2636
Bachelor       2590
PhD            2559
Associate      1999
Name: count, dtype: int64
------------------------------
Attrition
Attrition
No     6753
Yes    6247
Name: count, dtype: int64
------------------------------
Region
Region
Asia Pacific     3927
Middle East      2816
North America    2132
Europe           2064
Latin America    2061
Name: count, dtype: int64
------------------------------
Payment_Method
Payment_Method
Wire Transfer     3576
Cash              3179
Check             3170
Direct Deposit    3075
Name: count, dtype: int64
------------------------------
Email
Email
Unknown                       659
employee_1@company.com          1
employee_8654@company.com       1
employee_8657@company.com       1
employee_8658@company.com       1
                             ...
employee_4319@company.com       1
employee_4320@company.com       1
employee_4322@company.com       1
employee_4323@company.com       1
employee_13000@company.com      1
Name: count, Length: 12342, dtype: int64
------------------------------

In [59]:
df.describe()

,Age,Hire_Date,Salary,Years_At_Company,Job_Satisfaction,Performance_Rating,Monthly_Hours
count,13000.000000,13000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000
mean,40.894846,2016-05-26 14:31:05.353846272,53837.889692,11.653923,3.063308,3.026846,57.082231
min,21.000000,2010-01-03 00:00:00,25000.000000,0.000000,1.000000,1.000000,35.000000
25%,32.000000,2015-05-05 00:00:00,25000.000000,5.000000,2.000000,2.000000,46.000000
50%,41.000000,2015-05-05 00:00:00,51823.000000,12.000000,3.000000,3.000000,57.000000
75%,50.000000,2018-08-07 06:00:00,74320.250000,18.000000,4.000000,4.000000,68.000000
max,60.000000,2023-12-30 00:00:00,168697.000000,24.000000,5.000000,5.000000,79.000000
std,11.367750,NaN,27117.756055,7.395616,1.439363,1.402185,12.815529

In [60]:
df.isin(["Nan", "nan", "--", "Unknown"]).sum()

EmployeeID              0
Full_Name               0
Age                     0
Gender                  0
Department              0
Job_Title               0
Education               0
Hire_Date               0
Salary                  0
Years_At_Company        0
Job_Satisfaction        0
Performance_Rating      0
Monthly_Hours           0
Attrition               0
Region                  0
Payment_Method          0
Email                 659
dtype: int64

In [61]:
print("Missing values:\n", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())
print("Shape:", df.shape)

Missing values:
 0
Duplicates: 0
Shape: (13000, 17)

In [62]:
df.to_csv("C:/Users/niveditha/OneDrive/Desktop/c_HR.csv",index=False)